export const profile = {
  lightBg: false,
  primary: true,
  imgStart: "",
  start: "",
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "",
  headLine: "Matteo Digiorgio",
  description: "Web Developer",
  visitable: "",
  downloadable: "",
  buttonLabel: "My GitHub",
  buttonLabelVisit: "",
  url: "https://github.com/MatteoDigiorgio",
  urlVisit: "",
  profile: "true",
  alt: "Image",
  img: "/me.jpg",
  imgWidth: "300",
  imgHeight: "300",
};

export const portfolio = {
  lightBg: true,
  primary: false,
  imgStart: "start",
  start: "true",
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Nextjs / React",
  headLine: "Portfolio",
  description: "This Portfolio created with Next.js and React",
  visitable: "",
  downloadable: "",
  buttonLabel: "View Code",
  buttonLabelVisit: "",
  url: "https://github.com/MatteoDigiorgio/Portfolio",
  urlVisit: "",
  profile: "",
  alt: "Image",
  img: "/portfolio.jpg",
  imgWidth: "600",
  imgHeight: "365",
};

export const foodazon = {
  lightBg: true,
  primary: false,
  imgStart: "",
  start: "",
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Mongodb / Expressjs / Angular / Nodejs",
  headLine: "foodazon",
  description: "Ecommerce for local markets",
  visitable: "true",
  downloadable: "",
  buttonLabel: "View Code",
  buttonLabelVisit: "Visit foodazon",
  url: "https://github.com/MatteoDigiorgio/foodazon",
  urlVisit: "https://foodazon.digiorgio.dev",
  profile: "",
  alt: "Image",
  img: "/foodazon.svg",
  imgWidth: "600",
  imgHeight: "365",
};

export const http3 = {
  lightBg: false,
  primary: true,
  imgStart: "start",
  start: "true",
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "Application Layer Protocol",
  headLine: "HTTP/3",
  description: "Thesis on the protocol of the future: HTTP/3",
  visitable: "",
  downloadable: "true",
  buttonLabel: "View Article",
  buttonLabelVisit: "",
  url: "/Matteo_Digiorgio_Thesis.pdf",
  urlVisit: "",
  profile: "",
  img: "/thesis.svg",
  alt: "Image",
  imgWidth: "400",
  imgHeight: "400",
};
