export const profile = {
  lightBg: false,
  primary: true,
  imgStart: "",
  start: "",
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "",
  headLine: "Matteo Digiorgio",
  description: "Web Developer",
  visitable: "",
  downloadable: "",
  buttonLabel: "My GitHub",
  buttonLabelVisit: "",
  url: "https://github.com/MatteoDigiorgio",
  urlVisit: "",
  profile: "true",
  alt: "Image",
  img: "/me.jpg",
  imgWidth: "300",
  imgHeight: "300",
};

export const portfolio = {
  lightBg: true,
  primary: false,
  imgStart: "start",
  start: "true",
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Nextjs / React",
  headLine: "Portfolio",
  description: "This Portfolio created with Next.js and React",
  visitable: "",
  downloadable: "",
  buttonLabel: "View Code",
  buttonLabelVisit: "",
  url: "https://github.com/MatteoDigiorgio/Portfolio",
  urlVisit: "",
  profile: "",
  alt: "Image",
  img: "/portfolio.jpg",
  imgWidth: "600",
  imgHeight: "365",
};

export const foodazon = {
  lightBg: true,
  primary: false,
  imgStart: "",
  start: "",
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Mongodb / Expressjs / Angular / Nodejs",
  headLine: "foodazon",
  description: "Ecommerce for local markets",
  visitable: "true",
  downloadable: "",
  buttonLabel: "View Code",
  buttonLabelVisit: "Visit foodazon",
  url: "https://github.com/MatteoDigiorgio/foodazon",
  urlVisit: "https://foodazon.digiorgio.dev",
  profile: "",
  alt: "Image",
  img: "/foodazon.svg",
  imgWidth: "600",
  imgHeight: "365",
};

export const linkedin = {
  lightBg: true,
  primary: false,
  imgStart: "start",
  start: "true",
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "React / Redux / Firebase",
  headLine: "Linkedin Clone",
  description: "Linkedin Clone created with React",
  visitable: "true",
  downloadable: "",
  buttonLabel: "View Code",
  buttonLabelVisit: "Visit Linkedin Clone",
  url: "https://github.com/MatteoDigiorgio/Linkedin-clone",
  urlVisit: "https://linkedin-clone.digiorgio.dev",
  profile: "",
  alt: "Image",
  img: "/linkedin.jpg",
  imgWidth: "600",
  imgHeight: "365",
};

export const amazon = {
  lightBg: true,
  primary: false,
  imgStart: "",
  start: "",
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Nextjs / React / Typescript / Redux / Firebase / NextAuth",
  headLine: "Amazon Clone",
  description: "Amazon Clone created with Next.js 13 and React",
  visitable: "true",
  downloadable: "",
  buttonLabel: "View Code",
  buttonLabelVisit: "Visit Amazon Clone",
  url: "https://github.com/MatteoDigiorgio/Amazon-clone",
  urlVisit: "https://amazon-clone.digiorgio.dev",
  profile: "",
  alt: "Image",
  img: "/amazon.jpg",
  imgWidth: "600",
  imgHeight: "365",
};

export const buymeacoffee = {
  lightBg: true,
  primary: false,
  imgStart: "start",
  start: "true",
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Nextjs / React / Javascript / Solidity / Hardhat / Wagmi",
  headLine: "Buy Me A Coffee DApp",
  description: "Buy Me A Coffee DApp built with Next.js 13, React, Solidity and Hardhat",
  visitable: "true",
  downloadable: "",
  buttonLabel: "View Code",
  buttonLabelVisit: "Visit Buy Matteo A Coffee",
  url: "https://github.com/MatteoDigiorgio/BuyMeACoffee",
  urlVisit: "https://buymeacoffee.digiorgio.dev",
  profile: "",
  alt: "Image",
  img: "/buymeacoffee.jpg",
  imgWidth: "600",
  imgHeight: "365",
};

export const http3 = {
  lightBg: false,
  primary: true,
  imgStart: "start",
  start: "true",
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "Application Layer Protocol",
  headLine: "HTTP/3",
  description: "Thesis on the protocol of the future: HTTP/3",
  visitable: "",
  downloadable: "true",
  buttonLabel: "Download PDF",
  buttonLabelVisit: "",
  url: "/Matteo_Digiorgio_Thesis.pdf",
  urlVisit: "",
  profile: "",
  img: "/thesis.svg",
  alt: "Image",
  imgWidth: "400",
  imgHeight: "400",
};
